uploads = []
generated = []

[[outputs]]
id = "Beah5U1zwrK24u2UvNXlA"
uri = "file://artifacts/grace-high-school/grace-high-school-website.tar.gz"
type = "unspecified"
title = "Grace High School Website (download)"

[[outputs]]
id = "HzwpdhNOXPOXj1DSRn7V0"
uri = "file://artifacts/grace-high-school/grace-high-school-website.zip"
type = "unspecified"
title = "Grace High School Website — grace-high-school-website.zip"
